POST http://localhost:3000/todo HTTP/1.1
Content-Type: application/json

{
    "title": "TEAMO",
    "description":"MIREYA"
}


###
PUT http://localhost:3000/todo/64cc7a7b5d951a80d8149413 HTTP/1.1
Content-Type: application/json

{
    "status": "COMPLETED",
    "description":"SEXO"
}

###
GET http://localhost:3000/todo HTTP/1.1

###

DELETE  http://localhost:3000/todo/64cc7a7b5d951a80d8149413 HTTP/1.1
